/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   moya.c                                             :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: Alexandr <Alexandr@student.42.fr>          +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2020/10/22 22:04:50 by Alexandr          #+#    #+#             */
/*   Updated: 2021/01/31 20:05:30 by Alexandr         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */
#ifndef GLOBAL_VARS_H
#define GLOBAL_VARS_H

double Vx[PARTICLE_NUMBER];
double Vy[PARTICLE_NUMBER];
double Vz[PARTICLE_NUMBER];
double coordx[PARTICLE_NUMBER];
double coordy[PARTICLE_NUMBER];
double coordz[PARTICLE_NUMBER];
double Fx[PARTICLE_NUMBER];
double Fy[PARTICLE_NUMBER];
double Fz[PARTICLE_NUMBER];

#endif