/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   moya.c                                             :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: Alexandr <Alexandr@student.42.fr>          +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2020/10/22 22:04:50 by Alexandr          #+#    #+#             */
/*   Updated: 2021/01/31 20:05:30 by Alexandr         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */
#ifndef GLOBAL_VARS_H
# define GLOBAL_VARS_H

extern double Vx[PARTICLE_NUMBER];
extern double Vy[PARTICLE_NUMBER];
extern double Vz[PARTICLE_NUMBER];
extern double coordx[PARTICLE_NUMBER];
extern double coordy[PARTICLE_NUMBER];
extern double coordz[PARTICLE_NUMBER];
extern double Fx[PARTICLE_NUMBER];
extern double Fy[PARTICLE_NUMBER];
extern double Fz[PARTICLE_NUMBER];

//static double *Vx = new double[PARTICLE_NUMBER];
//static double *Vy = new double[PARTICLE_NUMBER];
//static double *Vz = new double[PARTICLE_NUMBER];
//static double *coordx = new double[PARTICLE_NUMBER];
//static double *coordy = new double[PARTICLE_NUMBER];
//static double *coordz = new double[PARTICLE_NUMBER];
//static double *Fx = new double[PARTICLE_NUMBER];
//static double *Fy = new double[PARTICLE_NUMBER];
//static double *Fz = new double[PARTICLE_NUMBER];


#endif